"use client";

import { useEffect, useState } from "react";
import { Plus, Save } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/dashboard/page-header";
import { departuresService } from "@/services/departures.service";
import { Provider, PROVIDER_TYPE_LABELS, ProviderType } from "@/types/departures";
import { Agency } from "@/types/business";

export default function ProvidersPage() {
  const [providers, setProviders] = useState<Provider[]>([]); const [name, setName] = useState(""); const [type, setType] = useState<ProviderType>("GARAGE"); const [saving, setSaving] = useState<string | null>(null);
  const [agencies, setAgencies] = useState<Agency[]>([]); const [agencyId, setAgencyId] = useState("");
  async function load(id = agencyId) { if (id) setProviders(await departuresService.providers(id, true)); }
  useEffect(() => { const timer = window.setTimeout(() => void departuresService.agencies().then((data) => { setAgencies(data); const saved = window.localStorage.getItem("departures:agency-id"); setAgencyId(data.some((item) => item.id === saved) ? saved! : (data[0]?.id ?? "")); }), 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (!agencyId) return; window.localStorage.setItem("departures:agency-id", agencyId); const timer = window.setTimeout(() => void load(agencyId), 0); return () => window.clearTimeout(timer); }, [agencyId]);
  async function create() { if (!name.trim() || !agencyId) return; try { await departuresService.createProvider({ agencyId, name: name.trim(), type, displayOrder: providers.length }); setName(""); await load(); toast.success("Prestataire ajouté."); } catch { toast.error("Impossible d’ajouter ce prestataire."); } }
  async function save(item: Provider) { setSaving(item.id); try { await departuresService.updateProvider(item.id, { name: item.name, type: item.type, displayOrder: Number(item.displayOrder), isActive: item.isActive }); await load(); toast.success("Prestataire mis à jour."); } catch { toast.error("Mise à jour impossible."); } finally { setSaving(null); } }
  return <><PageHeader title="Prestataires" description="Gérez les colonnes du tableau des départs véhicules." /><div className="mb-4"><select aria-label="Agence" className="h-10 max-w-72 rounded-md border bg-white px-3 text-sm font-semibold" value={agencyId} onChange={(event) => setAgencyId(event.target.value)}>{agencies.map((agency) => <option key={agency.id} value={agency.id}>{agency.city} · {agency.name}</option>)}</select></div><div className="space-y-4 rounded-lg border bg-white p-5"><div className="grid gap-3 rounded-lg border border-dashed bg-slate-50 p-4 md:grid-cols-[1fr_220px_auto]"><Input placeholder="Nom du prestataire" value={name} onChange={(e) => setName(e.target.value)} /><select className="h-10 rounded-md border bg-white px-3 text-sm" value={type} onChange={(e) => setType(e.target.value as ProviderType)}>{Object.entries(PROVIDER_TYPE_LABELS).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><Button onClick={() => void create()}><Plus className="h-4 w-4" />Ajouter</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-3 py-3">Ordre</th><th className="px-3 py-3">Nom</th><th className="px-3 py-3">Type</th><th className="px-3 py-3">État</th><th className="px-3 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{providers.map((item) => <tr key={item.id}><td className="w-24 px-3 py-2"><Input type="number" value={item.displayOrder} onChange={(e) => setProviders((all) => all.map((p) => p.id === item.id ? { ...p, displayOrder: Number(e.target.value) } : p))} /></td><td className="px-3 py-2"><Input value={item.name} onChange={(e) => setProviders((all) => all.map((p) => p.id === item.id ? { ...p, name: e.target.value } : p))} /></td><td className="px-3 py-2"><select className="h-10 w-full rounded-md border bg-white px-3" value={item.type} onChange={(e) => setProviders((all) => all.map((p) => p.id === item.id ? { ...p, type: e.target.value as ProviderType } : p))}>{Object.entries(PROVIDER_TYPE_LABELS).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></td><td className="px-3 py-2"><label className="flex items-center gap-2"><input type="checkbox" checked={item.isActive} onChange={(e) => setProviders((all) => all.map((p) => p.id === item.id ? { ...p, isActive: e.target.checked } : p))} />Actif</label></td><td className="px-3 py-2 text-right"><Button variant="outline" disabled={saving === item.id} onClick={() => void save(item)}><Save className="h-4 w-4" />Enregistrer</Button></td></tr>)}</tbody></table></div></div></>;
}
